#
# Fission chart configuration
# 

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer.
serviceType: LoadBalancer

## Fission image repository
image: fission/fission-bundle

## Image pull policy
pullPolicy: IfNotPresent

## Fission image version
imageTag: v0.2.1

## Fission fetcher repository
fetcherImage: fission/fetcher

## Fission fetcher image version
fetcherImageTag: v0.2.1

## Port at which Fission controller service should be exposed
controllerPort: 31313

## Port at which Fission router service should be exposed
routerPort: 31314

## Port at which NATS streaming service should be exposed
natsStreamingPort: 31316

## Namespace in which to run fission functions (this is different from
## the release namespace)
functionNamespace: fission-function

## Set up openshift RBAC rule
openshift: false

## Logger config
logger:
  influxdbAdmin: "admin"
  fluentdImage: fission/fluentd

## Type of Queue you would like to use
## currently supports nats-streaming, azure-storage-queue
messageQueue:
  type: nats-streaming
  url: nats://defaultFissionAuthToken@nats-streaming:4222

## Message queue trigger config
### NATS Streaming
nats:
  authToken: "defaultFissionAuthToken"
  clusterID: "fissionMQTrigger"

## Required if messageQueue type is azure-storage-queue
azureStorageQueue:
  key: ""
  name: ""


## Persist data to a persistent volume.
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Analytics let us count how many people installed fission. Set to
## false to disable analytics.
analytics: true
